### ISSUE TITLE
Compare MD5 and path to determine if file already downloaded.

### ISSUE THREAD

**Issue by dalanmiller** [beaufour/flickr-download#26]
https://github.com/beaufour/flickr-download/blob/ce820275c2aa1663523cca6725a546748c1a1426/flickr_download/flick_download.py#L183

@beaufour to your knowledge does the Flickr API offer any sort of MD5 hash of the image data? Would be handy to not have to download it and instead just make a comparison against the local hash to the hash signature available in the API.

**Comment by beaufour** [comment]
@dalanmiller to be honest, I don't know, but looking around in the API docs it doesn't look like it. That said, their docs have never been the best. But maybe instead of MD5, one could do something date-based instead. Ie compare if the last modified date (which I would hope their api has :) ), with the local file date.

**Comment by brandongalbraith** [comment]
Possible solution is to do a [flickr.photos.getInfo](https://www.flickr.com/services/api/flickr.photos.getInfo.html) call and then set the MD5 hash to the image as a tag for future de-duplication. I spent ~20 minutes reviewing the developer docs, and no mention of a way to retrieve a hash of any sort from an image's metadata.

**Comment by beaufour** [comment]
I added a little metadata database instead which takes care of this.
